from dotenv import load_dotenv
import os

load_dotenv()

DATASETS_PATH = os.getenv("DATASETS_PATH") or os.getenv("DATASETS_ROOT", "")

BAS_RVG1_PATH = os.path.join(DATASETS_PATH, "BAS-RVG1/RVG1_CLARIN")
SWITCHBOARD_BENCHMARK_PATH = os.getenv("SWITCHBOARD_BENCHMARK_PATH")

VERBMOBIL_SMALL_PATH = os.getenv("VERBMOBIL_SMALL_PATH")
VERBMOBIL_SMALL_AUDIO_PATH = os.getenv("VERBMOBIL_SMALL_AUDIO_PATH")
VERBMOBIL_SMALL_TRL_PATH = os.getenv("VERBMOBIL_SMALL_TRL_FILE_PATH")

if VERBMOBIL_SMALL_PATH:
    if VERBMOBIL_SMALL_AUDIO_PATH is None:
        VERBMOBIL_SMALL_AUDIO_PATH = os.path.join(VERBMOBIL_SMALL_PATH, "SSG")
    if VERBMOBIL_SMALL_TRL_PATH is None:
        VERBMOBIL_SMALL_TRL_PATH = os.path.join(VERBMOBIL_SMALL_PATH, "verbmobil_small.trl")


OUTPUT_PATH = os.getenv("OUTPUT_PATH")
